### ISSUE TITLE
Fix /help in skilstak.slack.com

### ISSUE THREAD

**Issue by robmuh** [skilstak/internal-projects#3]
Figure out how to get /help to work with the slackbot if possible.

**Comment by rydens** [comment]
But why do we need that command, it is for getting help with slack, but you can just ask slackbot (in a direct conversation with it) for what you need

**Comment by rydens** [comment]
<img width="980" alt="screen shot 2016-08-22 at 9 54 44 pm" src="https://cloud.githubusercontent.com/assets/12144736/17877682/11f2d3b0-68b3-11e6-9674-6ff316f60cff.png">

**Comment by tslnc04** [comment]
The issue is the use of a preceding slash. The best I can do is just the word help, but that would be an issue for a lot of cases.

**Comment by robmuh** [comment]
It's ok to close this one since we have #help defaulting now. skilbot will cover the other fun stuff but even that is not as intuitive as just going into the #help room and asking a question
